name: Discord Bot

on:
  workflow_dispatch:


  schedule:
    - cron: "* * * * *"

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Discord script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          chmod +x exec.sh
          ./exec.sh
